#!/bin/sh

{{ ansible_managed | comment }}

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup

[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources

vncconfig -iconic &

dbus-launch --exit-with-session {{ tigervnc_desktop_session }} &
